DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS experiences;
ALTER TABLE users DROP COLUMN IF EXISTS social_links;
ALTER TABLE users DROP COLUMN IF EXISTS website_url;
ALTER TABLE users DROP COLUMN IF EXISTS location;
